### ISSUE TITLE
Need to install librsvg on Mac to use SVG format

### ISSUE THREAD

**Issue by phatmann** [raghur/mermaid-filter#108]
On macOS if you run mermaid-filter with the MERMAID_FILTER_FORMAT environment variable set to "svg", you will get the error:

```
Could not convert image /path/to/image/file: check that rsvg-convert is in path.
rsvg-convert: createProcess: posix_spawnp: does not exist (No such file or directory)
```

I ran `brew install librsvg` and that fixed the issue. Either the dependencies need to be updated or the docs updated.

**Comment by Kalankaboom** [comment]
I have had the exact same issue on Debian.
I am using a LaTeX font, here is my yaml
```yaml
header-includes:
    - \renewcommand*\familydefault{\sfdefault}
monofont: "BlexMono Nerd Font Mono"
```
